// data.js — All semester and project data for the portfolio

const PORTFOLIO_DATA = {
  owner: {
    name: "Muhammad Ahmed",
    location: "Karachi, Sindh, Pakistan",
    github: "https://github.com/muhammad-ahm/UniversityProjects",
    tagline: "Computer Science Student · Builder of Things",
  },

  semesters: [
    {
      id: "sem1",
      label: "Semester 1",
      status: "upcoming",
      color: "#94a3b8",
      icon: "🌱",
      projects: [],
      note: "Projects coming soon",
    },
    {
      id: "sem2",
      label: "Semester 2",
      status: "upcoming",
      color: "#94a3b8",
      icon: "🌿",
      projects: [],
      note: "Projects coming soon",
    },
    {
      id: "sem3",
      label: "Semester 3",
      status: "active",
      color: "#f97316",
      icon: "🔥",
      githubFolder: "https://github.com/muhammad-ahm/UniversityProjects/tree/main/3rdSemester",
      projects: [
        {
          id: "toexhek",
          title: "ToeXhek",
          subtitle: "DSA Sorting Adventure Game",
          description:
            "A two-player number guessing game where Player 1 sets a secret 4-digit number and Player 2 guesses it. All guesses are sorted using five algorithms with execution time comparison. Features a dark GTA-style theme and persistent history.",
          tags: ["Java", "Swing", "MySQL", "JDBC", "Maven", "JUnit 5"],
          type: "Game / DSA",
          icon: "🎮",
          highlight: "5 sorting algorithms compared live",
        },
        {
          id: "cpu-logisim",
          title: "Simple CPU Simulator",
          subtitle: "Built in Logisim",
          description:
            "An 8-bit CPU simulator following von Neumann architecture with a 4-bit address bus. Simulates the full fetch-decode-execute cycle using opcode-based control logic with 7-segment display output.",
          tags: ["Logisim", "CPU Design", "ALU", "Digital Logic"],
          type: "Hardware Simulation",
          icon: "⚙️",
          highlight: "Full instruction cycle simulation",
        },
        {
          id: "asm-toolkit",
          title: "Compact Assembly Toolkit",
          subtitle: "Multi-Module System-Level Project",
          description:
            "A modular x86 Assembly toolkit with five integrated modules: keyboard interrupt handling, arithmetic calculator, VGA graphics renderer, software CPU simulator, and self-modifying code demo.",
          tags: ["x86 Assembly", "BIOS Interrupts", "VGA", "DOS"],
          type: "Systems Programming",
          icon: "🖥️",
          highlight: "Self-modifying code at runtime",
        },
      ],
    },
    {
      id: "sem4",
      label: "Semester 4",
      status: "upcoming",
      color: "#94a3b8",
      icon: "📚",
      projects: [],
      note: "Projects coming soon",
    },
    {
      id: "sem5",
      label: "Semester 5",
      status: "upcoming",
      color: "#94a3b8",
      icon: "📚",
      projects: [],
      note: "Projects coming soon",
    },
    {
      id: "sem6",
      label: "Semester 6",
      status: "upcoming",
      color: "#94a3b8",
      icon: "📚",
      projects: [],
      note: "Projects coming soon",
    },
    {
      id: "sem7",
      label: "Semester 7",
      status: "upcoming",
      color: "#94a3b8",
      icon: "📚",
      projects: [],
      note: "Projects coming soon",
    },
    {
      id: "sem8",
      label: "Semester 8",
      status: "upcoming",
      color: "#94a3b8",
      icon: "🎓",
      projects: [],
      note: "Projects coming soon",
    },
  ],
};
